---

- hosts: all
  become: true

  handlers:
    - name: restart inetd
      service:
        name: inetd
        state: restarted

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Install telnet.
      apt:
        name:
          - telnet
          - telnetd
        state: present
      notify: restart inetd

  roles:
    - chrony
    - deekayen.meshchat
