---

- name: Install dependencies.
  ansible.builtin.apt:
    name:
      - gpsd
      - gpsd-clients
      - python3-gps
      - python3-gi-cairo
  notify:
    - Enable gpsd

- name: Copy gpsd configuration.
  ansible.builtin.template:
    src: gpsd.j2
    dest: /etc/default/gpsd
    owner: root
    group: root
    mode: '644'
  notify:
    - Enable gpsd

# lineinfile /etc/chrony/chrony.conf
# refclock SHM 0 offset 0.5 delay 0.2 refid NMEA
