---

- name: Install dependencies.
  apt:
    name:
      - gpsd
      - gpsd-clients
      - python-gps
      - chrony
      - python-gi-cairo
  notify:
    - enable gpsd
    - enable chronyd

- name: Copy gpsd configuration.
  copy:
    src: gpsd
    dest: /etc/default/gpsd
    owner: root
    group: root
    mode: 0644
  notify:
    - enable gpsd

- name: Copy chronyd configuration.
  copy:
    src: chrony.conf
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - enable chronyd
