---

- name: Install dependencies.
  ansible.builtin.apt:
    name:
      - chrony
      - python3-gi-cairo
  notify:
    - enable chronyd

- name: Copy chronyd configuration.
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - enable chronyd
